import { Planet, PlanetSummary } from "./types";

export const planets: Planet[] = [
  {
    id: "mercury",
    name: "Mercury",
    order: 1,
    type: "terrestrial",
    diameterKm: 4879,
    massKg: "3.30e23",
    distanceFromSunAU: 0.39,
    orbitalPeriodDays: 87.97,
    rotationPeriodHours: 1407.6,
    moonsCount: 0,
    hasRings: false,
    avgTemperatureCelsius: 167,
    description:
      "The smallest planet and closest to the Sun, with extreme temperature swings between day and night.",
  },
  {
    id: "venus",
    name: "Venus",
    order: 2,
    type: "terrestrial",
    diameterKm: 12104,
    massKg: "4.87e24",
    distanceFromSunAU: 0.72,
    orbitalPeriodDays: 224.7,
    rotationPeriodHours: -5832.5,
    moonsCount: 0,
    hasRings: false,
    avgTemperatureCelsius: 464,
    description:
      "The hottest planet due to its thick CO₂ atmosphere. It rotates retrograde, making the Sun rise in the west.",
  },
  {
    id: "earth",
    name: "Earth",
    order: 3,
    type: "terrestrial",
    diameterKm: 12756,
    massKg: "5.97e24",
    distanceFromSunAU: 1.0,
    orbitalPeriodDays: 365.25,
    rotationPeriodHours: 23.93,
    moonsCount: 1,
    hasRings: false,
    avgTemperatureCelsius: 15,
    description:
      "The only known planet harboring life, with liquid water on its surface and a protective magnetic field.",
  },
  {
    id: "mars",
    name: "Mars",
    order: 4,
    type: "terrestrial",
    diameterKm: 6792,
    massKg: "6.42e23",
    distanceFromSunAU: 1.52,
    orbitalPeriodDays: 686.97,
    rotationPeriodHours: 24.62,
    moonsCount: 2,
    hasRings: false,
    avgTemperatureCelsius: -65,
    description:
      "The Red Planet hosts the tallest volcano (Olympus Mons) and the longest canyon (Valles Marineris) in the solar system.",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    order: 5,
    type: "gas giant",
    diameterKm: 142984,
    massKg: "1.90e27",
    distanceFromSunAU: 5.2,
    orbitalPeriodDays: 4331,
    rotationPeriodHours: 9.93,
    moonsCount: 95,
    hasRings: true,
    avgTemperatureCelsius: -110,
    description:
      "The largest planet, with a Great Red Spot storm raging for centuries and a powerful magnetic field.",
  },
  {
    id: "saturn",
    name: "Saturn",
    order: 6,
    type: "gas giant",
    diameterKm: 120536,
    massKg: "5.68e26",
    distanceFromSunAU: 9.58,
    orbitalPeriodDays: 10747,
    rotationPeriodHours: 10.7,
    moonsCount: 146,
    hasRings: true,
    avgTemperatureCelsius: -140,
    description:
      "Iconic for its spectacular ring system made of ice and rock; its moon Titan has a thick nitrogen atmosphere.",
  },
  {
    id: "uranus",
    name: "Uranus",
    order: 7,
    type: "ice giant",
    diameterKm: 51118,
    massKg: "8.68e25",
    distanceFromSunAU: 19.2,
    orbitalPeriodDays: 30589,
    rotationPeriodHours: -17.24,
    moonsCount: 28,
    hasRings: true,
    avgTemperatureCelsius: -195,
    description:
      "Rotates on its side with an axial tilt of 98°, giving it extreme seasons that each last over 20 years.",
  },
  {
    id: "neptune",
    name: "Neptune",
    order: 8,
    type: "ice giant",
    diameterKm: 49528,
    massKg: "1.02e26",
    distanceFromSunAU: 30.05,
    orbitalPeriodDays: 59800,
    rotationPeriodHours: 16.11,
    moonsCount: 16,
    hasRings: true,
    avgTemperatureCelsius: -200,
    description:
      "The windiest planet, with gusts up to 2100 km/h. Its large moon Triton orbits in the opposite direction.",
  },
];
